image: Visual Studio 2015
configuration: Release
platform:
  - x64
clone_folder: C:\projects\calyp

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64'
  - cd C:\projects
  - git clone https://github.com/ChristianFeldmann/Qt5-YUView-MT Qt --depth 1
  - set QTDIR=C:\projects\Qt\5.11-release
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  # activate the automatic update feature
  - cd C:\projects\calyp
  - mkdir build
  - cd build
  - cmake ..
  - where nmake
  - nmake
