image: Visual Studio 2017
configuration: Release
platform:
  - x64
clone_folder: C:\projects\calyp

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64'
  #- choco install ffmpeg
  - choco install nsis
  - choco install opencv
  #- 'C:\Tools\opencv\build\setup_vars_opencv4.cmd'
  - cd C:\projects
  #- git clone https://github.com/ChristianFeldmann/Qt5-YUView-MT Qt --depth 1
  #- set QTDIR=C:\projects\Qt\5.11-release
  #- set PATH=%PATH%;%QTDIR%\bin
  - ps: Start-FileDownload 'https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.1.1-win64-dev.zip'
  #- 7z e ffmpeg-4.1.1-win64-dev.zip

build_script:
  - cd C:\projects\calyp
  - mkdir build
  - cd build
  - cmake -DUSE_DYNLOAD=OFF -DOpenCV_DIR="C:/Tools/opencv/build/" -DOpenCV_DLL_DIR="C:/Tools/opencv/build/x64/vc15/bin" -DQT_DIR="C:\Qt\latest\msvc2017_64" -DQt5_DIR="C:/Qt/latest/msvc2017_64/lib/cmake/Qt5" -G "Visual Studio 15 2017 Win64" ..
  - cmake --build . --target ALL_BUILD > log_build
  - cmake --build . --target INSTALL > log_install
  #- cmake --build . --target PACKAGE > log_pkg


on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
